sudo: required
language: generic
services: docker

branches:
  only:
  - master

cache:
  directories:
    - $HOME/.cache/Tectonic

script:
  # We use the docker image from https://hub.docker.com/r/dxjoke/tectonic-docker/
  - docker pull dxjoke/tectonic-docker
  # Compiling only main.tex:
  - docker run --mount src=$TRAVIS_BUILD_DIR/,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic MastodonManual.tex"
  - ls -r 
  - git checkout --orphan $TRAVIS_BRANCH-pdf
  - git add -f MastodonManual.pdf
  - git -c user.name='travis' -c user.email='travis' commit -m "Building the manual."
  - git push -q -f https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG $TRAVIS_BRANCH-pdf
